# Generated by Django 4.2 on 2025-05-13 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': True, 'ordering': ['-data_inicio'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='end_date',
            new_name='data_fim',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='start_date',
            new_name='data_inicio',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='end_hour',
            new_name='hora_fim',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='start_hour',
            new_name='hora_inicio',
        ),
    ]
