# Generated by Django 4.2 on 2025-05-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_inicio',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_fim',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
    ]
