# Generated by Django 4.2 on 2025-07-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_reserva_hora_fim_remove_reserva_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='cor',
            field=models.CharField(default='#034efc', max_length=7),
        ),
    ]
